# Generated by Django 2.2 on 2022-05-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='caption',
            field=models.TextField(max_length=200),
        ),
    ]
