# Generated by Django 2.2 on 2022-05-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220511_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='wow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(max_length=200)),
                ('text', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='number',
        ),
    ]
