# Generated by Django 2.2 on 2022-05-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220511_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wow',
            name='text',
        ),
    ]
