# Generated by Django 2.2 on 2022-05-12 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_tools'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tools',
        ),
    ]
