# Generated by Django 2.2 on 2022-05-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20220512_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wow',
            name='caption',
            field=models.TextField(max_length=200),
        ),
    ]
