# Generated by Django 2.2 on 2022-05-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20220512_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='cute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='wow',
        ),
    ]
