# Generated by Django 2.2 on 2022-05-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_comment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='map',
            field=models.CharField(max_length=1000),
        ),
    ]
