# Generated by Django 2.2 on 2022-05-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20220514_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='track_one',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trac', models.CharField(max_length=300)),
            ],
        ),
    ]
