# Generated by Django 2.2 on 2022-05-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_track_one'),
    ]

    operations = [
        migrations.DeleteModel(
            name='track_one',
        ),
    ]
