# Generated by Django 2.2 on 2022-05-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_track_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='cons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('true', models.CharField(max_length=200)),
                ('trac_one', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='trackId',
        ),
    ]
