# Generated by Django 2.2 on 2022-05-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20220514_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='location_two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('previous_location', models.CharField(max_length=200)),
                ('current_location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('delivery_date', models.CharField(max_length=200)),
                ('map', models.CharField(max_length=1000)),
            ],
        ),
    ]
